# Store all our doggos here
module Doggos
  def self.hypo_doggos
    ['Affenpinscher',
     'Afghan Hound',
     'Airedale Terrier',
     'American Hairless Terrier',
     'Australian Terrier',
     'Basenji',
     'Bedlington Terrier',
     'Bichon Frise',
     'Bolognese',
     'Border Terrier',
     'Bouvier des Flanders',
     'Brussels Griffon',
     'Cairn Terrier',
     'Chinese Crested Dog',
     'Chinook',
     'Cockapoo',
     'Coton de Tulear',
     'Dandi Dinmont Terrier',
     'Fox Terrier',
     'Giant Schnauzer',
     'Havanese',
     'Irish Terrier',
     'Italian Greyhound',
     'Kerry Blue Terrier',
     'Kyi Leo',
     'Lakeland Terrier',
     'Lhasa Apso',
     'Lowchen',
     'Maltese',
     'Mountain Cur',
     'Norfolk Terrier',
     'Norwich Terrier',
     'Peruvian Inca Orchid',
     'Polish Lowland Sheepdog',
     'Poodle',
     'Portuguese Water Dog',
     'Puli',
     'Samoyed',
     'Schnauzer',
     'Scottish Terrier Scottie',
     'Sealyham Terrier',
     'Shih Tzu',
     'Silky Terrier',
     'Spanish Water Dog',
     'Standard Poodle',
     'Standard Schnauzer',
     'Tibetan Terrier',
     'Welsh Terrier',
     'West Highland White Terrier Westie',
     'Wheaten Terrier',
     'Wire Fox Terrier',
     'Wire-haired Pointing Griffon',
     'Wirehaired Dachshund',
     'Wirehaired Terrier',
     'Xoloitzcuintle (Mexican Hairless)',
     'Yorkshire Terrier Yorkie']
  end
end
